Removing nova DB...
Updating conf file...
Parsing of /etc/nova/nova.conf...
Done
Endpoint already created
Create database tables
2015-04-12 18:09:53.706 20 CRITICAL nova [-] OperationalError: (OperationalError) (1045, "Access denied for user 'nova'@'172.17.42.1' (using password: YES)") None None
2015-04-12 18:09:53.706 20 TRACE nova Traceback (most recent call last):
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/bin/nova-manage", line 10, in <module>
2015-04-12 18:09:53.706 20 TRACE nova     sys.exit(main())
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/nova/cmd/manage.py", line 1401, in main
2015-04-12 18:09:53.706 20 TRACE nova     ret = fn(*fn_args, **fn_kwargs)
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/nova/cmd/manage.py", line 902, in sync
2015-04-12 18:09:53.706 20 TRACE nova     return migration.db_sync(version)
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/nova/db/migration.py", line 29, in db_sync
2015-04-12 18:09:53.706 20 TRACE nova     return IMPL.db_sync(version=version)
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/migration.py", line 41, in db_sync
2015-04-12 18:09:53.706 20 TRACE nova     current_version = db_version()
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/migration.py", line 53, in db_version
2015-04-12 18:09:53.706 20 TRACE nova     return versioning_api.db_version(get_engine(), repository)
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.py", line 96, in get_engine
2015-04-12 18:09:53.706 20 TRACE nova     facade = _create_facade_lazily()
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.py", line 91, in _create_facade_lazily
2015-04-12 18:09:53.706 20 TRACE nova     _ENGINE_FACADE = db_session.EngineFacade.from_config(CONF)
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/oslo/db/sqlalchemy/session.py", line 795, in from_config
2015-04-12 18:09:53.706 20 TRACE nova     retry_interval=conf.database.retry_interval)
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/oslo/db/sqlalchemy/session.py", line 711, in __init__
2015-04-12 18:09:53.706 20 TRACE nova     **engine_kwargs)
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/oslo/db/sqlalchemy/session.py", line 386, in create_engine
2015-04-12 18:09:53.706 20 TRACE nova     connection_trace=connection_trace
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/oslo/db/sqlalchemy/utils.py", line 890, in __call__
2015-04-12 18:09:53.706 20 TRACE nova     self._url_from_target(target), target, arg, kw)
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/oslo/db/sqlalchemy/utils.py", line 927, in _dispatch_on
2015-04-12 18:09:53.706 20 TRACE nova     return self._dispatch_on_db_driver(dbname, driver, arg, kw)
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/oslo/db/sqlalchemy/utils.py", line 981, in _dispatch_on_db_driver
2015-04-12 18:09:53.706 20 TRACE nova     if self._invoke_fn(fn, arg, kw) is not None:
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/oslo/db/sqlalchemy/utils.py", line 930, in _invoke_fn
2015-04-12 18:09:53.706 20 TRACE nova     return fn(*arg, **kw)
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/oslo/db/sqlalchemy/session.py", line 456, in _init_events
2015-04-12 18:09:53.706 20 TRACE nova     realmode = engine.execute("SHOW VARIABLES LIKE 'sql_mode'").fetchone()
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1751, in execute
2015-04-12 18:09:53.706 20 TRACE nova     connection = self.contextual_connect(close_with_result=True)
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1799, in contextual_connect
2015-04-12 18:09:53.706 20 TRACE nova     self.pool.connect(),
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 338, in connect
2015-04-12 18:09:53.706 20 TRACE nova     return _ConnectionFairy._checkout(self)
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 641, in _checkout
2015-04-12 18:09:53.706 20 TRACE nova     fairy = _ConnectionRecord.checkout(pool)
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 440, in checkout
2015-04-12 18:09:53.706 20 TRACE nova     rec = pool._do_get()
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 961, in _do_get
2015-04-12 18:09:53.706 20 TRACE nova     return self._create_connection()
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 285, in _create_connection
2015-04-12 18:09:53.706 20 TRACE nova     return _ConnectionRecord(self)
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 411, in __init__
2015-04-12 18:09:53.706 20 TRACE nova     self.connection = self.__connect()
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 537, in __connect
2015-04-12 18:09:53.706 20 TRACE nova     connection = self.__pool._creator()
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 96, in connect
2015-04-12 18:09:53.706 20 TRACE nova     connection_invalidated=invalidated
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
2015-04-12 18:09:53.706 20 TRACE nova     reraise(type(exception), exception, tb=exc_tb)
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 90, in connect
2015-04-12 18:09:53.706 20 TRACE nova     return dialect.connect(*cargs, **cparams)
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 377, in connect
2015-04-12 18:09:53.706 20 TRACE nova     return self.dbapi.connect(*cargs, **cparams)
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
2015-04-12 18:09:53.706 20 TRACE nova     return Connection(*args, **kwargs)
2015-04-12 18:09:53.706 20 TRACE nova   File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__
2015-04-12 18:09:53.706 20 TRACE nova     super(Connection, self).__init__(*args, **kwargs2)
2015-04-12 18:09:53.706 20 TRACE nova OperationalError: (OperationalError) (1045, "Access denied for user 'nova'@'172.17.42.1' (using password: YES)") None None
2015-04-12 18:09:53.706 20 TRACE nova 
Command failed, please check log for more info
Starting nova using supervisord...
/usr/lib/python2.7/dist-packages/supervisor/options.py:295: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2015-04-12 18:09:53,863 CRIT Supervisor running as root (no user in config file)
2015-04-12 18:09:53,865 INFO supervisord started with pid 1
2015-04-12 18:09:54,868 INFO spawned: 'nova-novncproxy' with pid 28
2015-04-12 18:09:54,870 INFO spawned: 'nova-cert' with pid 29
2015-04-12 18:09:54,871 INFO spawned: 'nova-conductor' with pid 30
2015-04-12 18:09:54,873 INFO spawned: 'nova-api' with pid 31
2015-04-12 18:09:54,879 INFO spawned: 'nova-consoleauth' with pid 32
2015-04-12 18:09:54,880 INFO spawned: 'nova-scheduler' with pid 33
2015-04-12 18:09:55,882 INFO success: nova-novncproxy entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-12 18:09:55,882 INFO success: nova-cert entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-12 18:09:55,882 INFO success: nova-conductor entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-12 18:09:55,882 INFO success: nova-api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-12 18:09:55,882 INFO success: nova-consoleauth entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-12 18:09:55,882 INFO success: nova-scheduler entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-12 18:09:57,794 INFO exited: nova-consoleauth (exit status 0; expected)
2015-04-12 18:09:57,893 INFO spawned: 'nova-consoleauth' with pid 75
2015-04-12 18:09:57,894 INFO exited: nova-scheduler (exit status 0; expected)
2015-04-12 18:09:57,913 INFO spawned: 'nova-scheduler' with pid 77
2015-04-12 18:09:58,182 INFO exited: nova-cert (exit status 0; expected)
2015-04-12 18:09:58,237 INFO spawned: 'nova-cert' with pid 86
2015-04-12 18:09:59,122 INFO success: nova-consoleauth entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-12 18:09:59,122 INFO success: nova-scheduler entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-12 18:09:59,556 INFO success: nova-cert entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-12 18:09:59,913 INFO exited: nova-consoleauth (exit status 0; expected)
2015-04-12 18:10:00,039 INFO spawned: 'nova-consoleauth' with pid 105
2015-04-12 18:10:00,234 INFO exited: nova-scheduler (exit status 0; expected)
2015-04-12 18:10:00,291 INFO spawned: 'nova-scheduler' with pid 109
2015-04-12 18:10:00,425 INFO exited: nova-cert (exit status 0; expected)
2015-04-12 18:10:00,662 INFO spawned: 'nova-cert' with pid 116
2015-04-12 18:10:01,376 INFO success: nova-consoleauth entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-12 18:10:01,376 INFO success: nova-scheduler entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-12 18:10:01,663 INFO success: nova-cert entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-12 18:10:02,082 INFO exited: nova-consoleauth (exit status 0; expected)
2015-04-12 18:10:02,163 INFO spawned: 'nova-consoleauth' with pid 129
2015-04-12 18:10:02,371 INFO exited: nova-scheduler (exit status 0; expected)
2015-04-12 18:10:02,515 INFO spawned: 'nova-scheduler' with pid 134
2015-04-12 18:10:02,714 INFO exited: nova-cert (exit status 0; expected)
2015-04-12 18:10:02,718 INFO spawned: 'nova-cert' with pid 141
2015-04-12 18:10:03,600 INFO success: nova-consoleauth entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-12 18:10:03,600 INFO success: nova-scheduler entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-12 18:10:03,782 INFO success: nova-cert entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-12 18:10:03,998 INFO exited: nova-consoleauth (exit status 0; expected)
2015-04-12 18:10:04,043 INFO spawned: 'nova-consoleauth' with pid 152
2015-04-12 18:10:04,587 INFO exited: nova-scheduler (exit status 0; expected)
2015-04-12 18:10:04,647 INFO spawned: 'nova-scheduler' with pid 158
2015-04-12 18:10:04,838 INFO exited: nova-cert (exit status 0; expected)
2015-04-12 18:10:05,196 INFO spawned: 'nova-cert' with pid 166
2015-04-12 18:10:05,197 INFO success: nova-consoleauth entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-12 18:10:05,705 INFO success: nova-scheduler entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-12 18:10:05,830 INFO exited: nova-consoleauth (exit status 0; expected)
2015-04-12 18:10:06,040 INFO spawned: 'nova-consoleauth' with pid 176
2015-04-12 18:10:06,266 INFO success: nova-cert entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-12 18:10:06,266 INFO exited: nova-scheduler (exit status 0; expected)
2015-04-12 18:10:06,322 INFO spawned: 'nova-scheduler' with pid 179
2015-04-12 18:10:07,042 INFO success: nova-consoleauth entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-12 18:10:07,242 INFO exited: nova-cert (exit status 0; expected)
2015-04-12 18:10:07,305 INFO spawned: 'nova-cert' with pid 190
2015-04-12 18:10:07,440 INFO success: nova-scheduler entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

